### ISSUE TITLE
Autocommand throws error in v0.11.0-dev

### ISSUE THREAD

**Issue by GordianDziwis** [nvimtools/none-ls.nvim#214] opened 2024-12-04 11:27 UTC
I am on the Neovim nightly: NVIM v0.11.0-dev, and this version guard seems to not working correctly:

https://github.com/nvimtools/none-ls.nvim/blob/58866c670d68ef80397c317a3a1ee5f53ca646fd/lua/null-ls/client.lua#L205

This line throws an error:

```txt
Error detected while processing InsertLeave Autocommands for "*":
Error executing lua callback: ...ocal/share/nvim/plugged/none-ls.nvim/lua/null-ls/rpc.lua:144: attempt to
concatenate local 'method' (a table value)
stack traceback:
        ...ocal/share/nvim/plugged/none-ls.nvim/lua/null-ls/rpc.lua:144: in function 'notify'
        /usr/share/nvim/runtime/lua/vim/lsp/client.lua:778: in function 'notify'
        ...l/share/nvim/plugged/none-ls.nvim/lua/null-ls/client.lua:205: in function 'notify_client'
        ...ocal/share/nvim/plugged/none-ls.nvim/lua/null-ls/rpc.lua:163: in function 'flush'
        ...cal/share/nvim/plugged/none-ls.nvim/lua/null-ls/init.lua:49: in function <...cal/share/nvim/plu
gged/none-ls.nvim/lua/null-ls/init.lua:48>
```

When I change the line to:

```lua
        client.notify(method, params)
```

it works.

**Comment by mochaaP** [comment] 2024-12-04 20:25
duplicate of #209 #213, please update neovim or switch to stable.

**Closed** 2024-12-04 20:25 UTC
