### ISSUE TITLE
Bug: None-ls clients not loading anymore after the recent commits

### ISSUE THREAD

**Issue by Zeioth** [nvimtools/none-ls.nvim#88] opened 2024-03-05 19:18 UTC
### FAQ

- [X] I have checked the [FAQ](https://github.com/nvimtools/none-ls.nvim#faq) and it didn't resolve my problem.

### Issues

- [X] I have checked [existing issues](https://github.com/nvimtools/none-ls.nvim/issues?q=is%3Aissue) and there are no issues with the same problem.

### Neovim Version

v0.9.5

### Dev Version?

- [ X] I am using a stable Neovim release version, or if I am using a dev version of Neovim I have confirmed that my issue is reproducible on a stable version.

### Operating System

arch

### Minimal Config

```Lua
x
```

### Steps to Reproduce

x

### Reproducibility Check

- [ ] I confirm that my minimal config is based on the `minimal_init.lua` template and that my issue is reproducible by running `nvim --clean -u minimal_init.lua` and following the steps above.

### Expected Behavior

x

### Actual Behavior

x

### Debug Log

x

### Help

No

### Implementation Help

After the commit 92a0251280ae2cce790ce5733e223459a57567d0 my previous config has stopped to work.

```lua
    opts = function()
      local nls = require "null-ls"
      return {
        sources = {
          -- You can customize your formatters here.
          nls.builtins.formatting.beautysh.with {
            command = "beautysh",
            args = { "--indent-size=2", "$FILENAME" },
          },
          -- TODO: Disable the next feature once this has been merged.
          -- https://github.com/bash-lsp/bash-language-server/issues/933
          nls.builtins.code_actions.shellcheck,
          nls.builtins.diagnostics.shellcheck.with { diagnostics_format = "" },
        },
        on_attach = utils_lsp.apply_user_lsp_settings,
      }
```

What's the new way to do this?

### Requirements

- [X] I have read and followed the instructions above and understand that my issue will be closed if I did not provide the required information.

**Comment by Zeioth** [comment] 2024-03-05 19:19
![screenshot_2024-03-05_20-17-08_206531506](https://github.com/nvimtools/none-ls.nvim/assets/3357792/f3f88841-5d52-4e57-8d9e-8e6bd86ecc01)

**Comment by Zeioth** [comment] 2024-03-06 00:16
![screenshot_2024-03-06_01-16-15_860951787](https://github.com/nvimtools/none-ls.nvim/assets/3357792/e9155e5c-0375-4ce3-8e86-c87a412c67b0)

**Comment by Zeioth** [comment] 2024-03-06 00:19
If I comment the lines above, I don't get the error anymore, but still none-ls doesn't seem to load its clients normally anymore.
![screenshot_2024-03-06_01-17-09_313894963](https://github.com/nvimtools/none-ls.nvim/assets/3357792/ee6f0431-81a7-48d4-bb3b-59da8b5dede0)


Normally they load with the plugin `jay-babu/mason-null-ls.nvim`. Maybe these last commits break compatibility with it?

If I run `NullLsInfo` I get this:
![screenshot_2024-03-06_01-18-33_936655183](https://github.com/nvimtools/none-ls.nvim/assets/3357792/0be17674-ddbd-4599-94ac-3407787c1756)

I'm updating to HEAD from d991c8952defd654ed78cce0abce63a5c06d0bc6, commit where everything was working OK.

**Comment by mochaaP** [comment] 2024-03-06 04:59
Duplicate of #81, search `beautysh` in the thread.

**Closed by mochaaP** 2024-03-06 04:59 UTC
Labels: bug
